apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wary
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wary
    app.kubernetes.io/part-of: my-cool-golang
  name: devfile-sample-wary
  namespace: mjobanek-tenant
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-wary
    weight: null
status: {}
